// <auto-generated />
using System;
using LagerPro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LagerPro.Infrastructure.Migrations
{
    [DbContext(typeof(LagerProDbContext))]
    [Migration("20260329092643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("LagerPro.Domain.Entities.Artikkel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtikkelNr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enhet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Innpris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinBeholdning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strekkode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Utpris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArtikkelNr")
                        .IsUnique();

                    b.ToTable("Artikler", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Epost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kontaktperson")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgNr")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postnr")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Poststed")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kunder", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.LagerBeholdning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikkelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BestForDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enhet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lokasjon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mengde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("SistOppdatert")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtikkelId", "LotNr")
                        .IsUnique();

                    b.ToTable("LagerBeholdninger", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.LagerTransaksjon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikkelId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BeholdningEtter")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Kilde")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KildeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mengde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("Tidspunkt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UtfortAv")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtikkelId");

                    b.ToTable("LagerTransaksjoner", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Leverandor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Epost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kontaktperson")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgNr")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postnr")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Poststed")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leverandorer", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Levering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FraktBrev")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("KundeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LeveringsDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("LevertAv")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referanse")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Leveringer", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.LeveringLinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikkelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enhet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeveringId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotNr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mengde")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ArtikkelId");

                    b.HasIndex("LeveringId");

                    b.ToTable("LeveringLinjer", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Mottak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeverandorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MottaksDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("MottattAv")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referanse")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeverandorId");

                    b.ToTable("Mottak", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.MottakLinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikkelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avvik")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BestForDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enhet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Godkjent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mengde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("MottakId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strekkode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperatur")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArtikkelId");

                    b.HasIndex("MottakId");

                    b.ToTable("MottakLinjer", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ProdOrdreForbruk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikkelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enhet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MengdeBrukt")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("Overstyrt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdOrdreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtikkelId");

                    b.HasIndex("ProdOrdreId");

                    b.ToTable("ProdOrdreForbruk", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ProduksjonsOrdre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AntallProdusert")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("FerdigmeldtDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("FerdigvareLotNr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdreNr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanlagtDato")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReseptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UtfortAv")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdreNr")
                        .IsUnique();

                    b.HasIndex("ReseptId");

                    b.ToTable("ProduksjonsOrdre", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ProduksjonsOrdreVersjon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AntallProdusert")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FerdigmeldtDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("FerdigvareLotNr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduksjonsOrdreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UtfortAv")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersjonsNummer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProduksjonsOrdreId");

                    b.ToTable("ProduksjonsOrdreVersjoner", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Resept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AntallPortjoner")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FerdigvareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instruksjoner")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SistEndret")
                        .HasColumnType("TEXT");

                    b.Property<int>("Versjon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FerdigvareId");

                    b.ToTable("Resepter", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ReseptLinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enhet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mengde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("RavareId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReseptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RavareId");

                    b.HasIndex("ReseptId");

                    b.ToTable("ReseptLinjer", (string)null);
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.LagerBeholdning", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Artikkel", "Artikkel")
                        .WithMany("LagerBeholdninger")
                        .HasForeignKey("ArtikkelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artikkel");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.LagerTransaksjon", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Artikkel", "Artikkel")
                        .WithMany("LagerTransaksjoner")
                        .HasForeignKey("ArtikkelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artikkel");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Levering", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Kunde", "Kunde")
                        .WithMany("Leveringer")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.LeveringLinje", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Artikkel", "Artikkel")
                        .WithMany("LeveringLinjer")
                        .HasForeignKey("ArtikkelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LagerPro.Domain.Entities.Levering", "Levering")
                        .WithMany("Linjer")
                        .HasForeignKey("LeveringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikkel");

                    b.Navigation("Levering");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Mottak", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Leverandor", "Leverandor")
                        .WithMany("Mottak")
                        .HasForeignKey("LeverandorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leverandor");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.MottakLinje", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Artikkel", "Artikkel")
                        .WithMany("MottakLinjer")
                        .HasForeignKey("ArtikkelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LagerPro.Domain.Entities.Mottak", "Mottak")
                        .WithMany("Linjer")
                        .HasForeignKey("MottakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikkel");

                    b.Navigation("Mottak");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ProdOrdreForbruk", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Artikkel", "Artikkel")
                        .WithMany("ProdOrdreForbruk")
                        .HasForeignKey("ArtikkelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LagerPro.Domain.Entities.ProduksjonsOrdre", "ProduksjonsOrdre")
                        .WithMany("Forbruk")
                        .HasForeignKey("ProdOrdreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikkel");

                    b.Navigation("ProduksjonsOrdre");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ProduksjonsOrdre", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Resept", "Resept")
                        .WithMany("ProduksjonsOrdre")
                        .HasForeignKey("ReseptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resept");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ProduksjonsOrdreVersjon", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.ProduksjonsOrdre", "ProduksjonsOrdre")
                        .WithMany()
                        .HasForeignKey("ProduksjonsOrdreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduksjonsOrdre");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Resept", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Artikkel", "Ferdigvare")
                        .WithMany()
                        .HasForeignKey("FerdigvareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ferdigvare");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ReseptLinje", b =>
                {
                    b.HasOne("LagerPro.Domain.Entities.Artikkel", "Ravare")
                        .WithMany("ReseptLinjer")
                        .HasForeignKey("RavareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LagerPro.Domain.Entities.Resept", "Resept")
                        .WithMany("Linjer")
                        .HasForeignKey("ReseptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ravare");

                    b.Navigation("Resept");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Artikkel", b =>
                {
                    b.Navigation("LagerBeholdninger");

                    b.Navigation("LagerTransaksjoner");

                    b.Navigation("LeveringLinjer");

                    b.Navigation("MottakLinjer");

                    b.Navigation("ProdOrdreForbruk");

                    b.Navigation("ReseptLinjer");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Kunde", b =>
                {
                    b.Navigation("Leveringer");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Leverandor", b =>
                {
                    b.Navigation("Mottak");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Levering", b =>
                {
                    b.Navigation("Linjer");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Mottak", b =>
                {
                    b.Navigation("Linjer");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.ProduksjonsOrdre", b =>
                {
                    b.Navigation("Forbruk");
                });

            modelBuilder.Entity("LagerPro.Domain.Entities.Resept", b =>
                {
                    b.Navigation("Linjer");

                    b.Navigation("ProduksjonsOrdre");
                });
#pragma warning restore 612, 618
        }
    }
}
